name: cd

on:
  workflow_run:
    workflows: [ 'ci' ]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure git credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --only docs

      - name: Deploy documentation
        run: poetry run mkdocs gh-deploy --force
